import { createElement } from 'lwc';
import Challenge7 from 'c/challenge7';
import { getRecord } from 'lightning/uiRecordApi';

const mockContact = require('./data/mockContact.json');
describe('c-challenge7', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic',async () => {
        // Arrange
        const element = createElement('c-challenge7', {
            is: Challenge7
        });
        
        // Act
        document.body.appendChild(element);

        getRecord.emit(mockContact);
        await Promise.resolve();
        
        const txtPhone = element.shadowRoot.querySelector('.phone');
        expect(txtPhone.textContent).toBe('Phone: (785) 241-6200');

        const txtName = element.shadowRoot.querySelector('.name');
        expect(txtName.textContent).toBe('Name: Andy Young');

        const txtTitle = element.shadowRoot.querySelector('.title');
        expect(txtTitle.textContent).toBe('Title: SVP, Operations');

        
    });
});